FROM golang:1.20-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Run tests
# RUN go test ./internal/db -v

# Build the main application
# RUN go build -o /automatic-sender ./cmd/main.go

CMD ["go", "test", "-v", "./..."]
