basePath: /
definitions:
  db.Message:
    properties:
      content:
        type: string
      id:
        type: integer
      recipient:
        type: string
      sentAt:
        $ref: '#/definitions/sql.NullTime'
    type: object
  sql.NullTime:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is an API for an automatic message sending system.
  title: Automatic Message Sending System API
  version: "1.0"
paths:
  /message-sending:
    post:
      consumes:
      - application/json
      description: Starts or stops the automatic message sending process
      parameters:
      - description: Action to perform
        enum:
        - start
        - stop
        in: query
        name: action
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Invalid action or already in desired state
          schema:
            type: string
      summary: Start or stop automatic message sending
      tags:
      - messages
  /sent-messages:
    get:
      consumes:
      - application/json
      description: Retrieves a list of sent messages
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.Message'
            type: array
        "500":
          description: Error retrieving sent messages
          schema:
            type: string
      summary: Retrieve sent messages
      tags:
      - messages
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-ins-auth-key
    type: apiKey
swagger: "2.0"
